# Generated by Django 4.1.1 on 2022-09-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.IntegerField(choices=[('PHONE', 'Phone'), ('FACEBOOK', 'Facebook'), ('EMAIL', 'Email')]),
        ),
    ]
