# Generated by Django 4.1.1 on 2022-09-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category_alter_course_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='courses.branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='contacts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='courses.contact'),
            preserve_default=False,
        ),
    ]
